version: '3'

services:
  similar:
    build: .
    depends_on:
      - 'database'
    ports: 
      - '80:3003'

  database:
    image: mongo:latest

  # proxy:
  #   build: proxy/
  #   depends_on:
  #     - 'smilar'
  #   ports:
  #     - '4000:4000'

  # database:
  #   image: mongo:latest

  # docker tag imageID ischulz/similar:initial
  # docker push ischulz/similar:initial